package com.example.demo.student;

import java.time.LocalDate;
import java.time.Month;
import java.util.List;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class StudentConfig {
    
    @Bean
    CommandLineRunner commandLineRunner(StudentRepository repository){
        return args -> {
            Student kyle = new Student(
				1L,
				"Kyle",
				"test@gmail.com",
				LocalDate.of(2000, Month.JANUARY, 28)
			);

            Student mikey = new Student( //id is auto generated by db
				"Mikey",
				"antTest@gmail.com",
				LocalDate.of(1996, Month.FEBRUARY, 4)
			);

            repository.saveAll(
                List.of(kyle, mikey)
            );
        };
    }
}
